name: Deploy Docker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: Docker-react-dev
        existing_bucket_name: elasticbeanstalk-eu-west-3-850316528551
        region: eu-west-3
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip